name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        # Artifact name
        name: artifact # optional
        # Destination path
        path: ./ # optional
    - run: |
          ls -ltr
      
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.13.5
          tf_actions_subcommand: 'init'
      env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
    
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.13.5
          tf_actions_subcommand: 'validate'
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.13.5
          tf_actions_subcommand: 'plan'
      env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.13.5
          tf_actions_subcommand: 'apply'
      env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
    - run: |
          ls -ltr ./
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        #name: terraform.tfstate # optional, default is artifact
        path: ./terraform.tfstate
