name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.12.13
          tf_actions_subcommand: 'init'
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.12.13
          tf_actions_subcommand: 'validate'
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.12.13
          tf_actions_subcommand: 'plan'
      env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
    - name: 'Terraform Destroy'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_working_dir: .
          tf_actions_version:  0.12.13
          tf_actions_subcommand: 'destroy'
      env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
   
